name: Update TestRail Test Case

on:
  issues:
    types: [closed]

jobs:
  update-testrail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update TestRail Test Case
        run: |
          # Set variables
          TESTRAIL_URL="https://ibm.testrail.io"
          TESTRAIL_API_KEY="${{ secrets.TESTRAIL_API_KEY }}"  # Use a GitHub secret for your API key
          TESTRAIL_USERNAME="${{ secrets.TESTRAIL_USERNAME }}"  # Use a GitHub secret for your username
          TESTRAIL_PROJECT_ID="387"
          TESTRAIL_SUITE_ID="9342"
          TESTRAIL_RUN_ID="133195"
          GITHUB_ISSUE_URL="${{ github.event.issue.html_url }}"

          # Extract the TestRail Test Case ID from the GitHub Issue body (e.g., #123)
          # ISSUE_BODY="${{ github.event.issue.body }}"
          # TESTCASE_ID=$(echo "$ISSUE_BODY" | grep -oP "#\d+" | tr -d '#')

          # Hardcoded Test Case ID for now
          TESTCASE_ID="21852725"
          echo "Updating TestRail Test Case ID: $TESTCASE_ID"

          # Update TestRail Test Case to 'Passed' (or any other desired status)
          curl -X POST "$TESTRAIL_URL/index.php?/api/v2/add_result_for_case/$TESTRAIL_RUN_ID/$TESTCASE_ID" \
            -u "$TESTRAIL_USERNAME:$TESTRAIL_API_KEY" \  # Pass username and API key for authentication
            -H "Content-Type: application/json" \
            -d "{\"status_id\": 1, \"comment\": \"Issue closed in GitHub: $GITHUB_ISSUE_URL\"}"
